#define SAVE_BOOKMARK_STRING "сохранить закладку"
#define LOAD_BOOKMARK_STRING "загрузить закладку"
#define IN_MENU_STRING "в меню"
#define GOTO_WORD_STRING "перейти к слову"
#define BACK_STRING "назад"
#define BIG_FONT_SIZE_STRING "большой"
#define SMALL_FONT_SIZE_STRING "маленький"
#define WIDE_FONT_SIZE_STRING "широкий"
#define READ_MODE_STRING "режим чтения"
#define SCROLL_STRING "прокрутка"
#define ONE_WORD_STRING "одно слово"
#define MANUAL_SCROLL_STRING "ручные страницы"
#define FONT_SIZE_STRING "размер текста"
#define SD_CARD_NOT_FOUND_STRING "SD карта не найдена"
#define RESUME_BOOK_YES "перейти к закладке"
#define RESUME_BOOK_NO "начать с начала"
#define RESUME_BOOK_TITLE "продолжить чтение"
#define RESUME_BOOK_TITLE_2 "с закладки?"
#define CONTRAST_STRING "контраст"
#define CONTRAST_LOW_STRING "низкий"
#define CONTRAST_HIGH_STRING "высокий"
