#define SAVE_BOOKMARK_STRING "save bookmark"
#define LOAD_BOOKMARK_STRING "load bookmark"
#define IN_MENU_STRING "back to menu"
#define GOTO_WORD_STRING "go to word"
#define BACK_STRING "back"
#define BIG_FONT_SIZE_STRING "large"
#define SMALL_FONT_SIZE_STRING "small"
#define WIDE_FONT_SIZE_STRING "wide"
#define READ_MODE_STRING "read mode"
#define SCROLL_STRING "scroll"
#define ONE_WORD_STRING "one word"
#define MANUAL_SCROLL_STRING "manual pages"
#define FONT_SIZE_STRING "font size"
#define SD_CARD_NOT_FOUND_STRING "SD card not found"
#define RESUME_BOOK_YES "from bookmark"
#define RESUME_BOOK_NO "from start"
#define RESUME_BOOK_TITLE "resume reading?"
#define RESUME_BOOK_TITLE_2 ""
